Widget enum attempt: MyEnum(Enum) outside class, pyqtProperty('MyEnum')
This caused the widget to not even show up in the Designer list.

(venv)altendky@tp:/epc/t/121/st.enum$ designer5
Traceback (most recent call last):
  File "/epc/t/121/st.enum/epyq/widgets/epcplugin.py", line 6, in <module>
    import epyq.widgets.epc
  File "/epc/t/121/st.enum/epyq/widgets/epc.py", line 23, in <module>
    class Epc(epyq.widgets.abstractwidget.AbstractWidget):
  File "/epc/t/121/st.enum/epyq/widgets/epc.py", line 36, in Epc
    @pyqtProperty('MyEnum')
TypeError: C++ type 'MyEnum' is not supported as a property type
NotImplementedError: QPyDesignerCustomWidgetPlugin.icon() is abstract and must be overridden
NotImplementedError: QPyDesignerCustomWidgetPlugin.icon() is abstract and must be overridden
NotImplementedError: QPyDesignerCustomWidgetPlugin.icon() is abstract and must be overridden
"contactsCompletionSession"
()
connectToServer "/tmp/akonadi-altendky.Xx4k3L/akonadiserver.socket"
Error while reparenting!
Designer: A class name mismatch occurred when creating a widget using the custom widget factory registered for widgets of class KDialog. It returned a widget of class QDialog.
QMetaProperty::read: Unable to handle unregistered datatype 'SelectionBehavior' for property 'QTabBar::selectionBehaviorOnRemove'
""
connectToServer "/tmp/akonadi-altendky.Xx4k3L/akonadiserver.socket"
log_mailcommon: Combobox destroyed
log_mailcommon: Combobox destroyed
done
Connected to "Akonadi" , using protocol version 51
Server says: "Not Really IMAP server"
Connected to "Akonadi" , using protocol version 51
Server says: "Not Really IMAP server"
(venv)altendky@tp:/epc/t/121/st.enum$